language: node_js 
node_js:
- "stable"

install:
- npm install
cache:
  directories:
    - "node_modules"

before_install:
- cd node

before_script:
- cd tests
- npm install mocha
- npm install chai
- npm chai-http

services:
- mongodb

