language: node_js 
node_js:
- "stable"

install:
- npm install
cache:
  directories:
    - "node_modules"

before_install:
- cd node

before_script:
- cd tests
- sleep 15
- npm install mocha
- npm install chai
- npm install chai-http

services:
- mongodb

var url = "mongodb://localhost:27017/madmenDB"; 
MongoClient.connect(url, function(err, db) {
  if (err) throw err;
  console.log("Database created");
  db.close();
}); 
