language: node_js 
node_js:
- "stable"

install:
- npm install
cache:
  directories:
    - "node_modules"

before_install:
- cd node

before_script:
- mongo mydb_test --eval 'db.products.insertOne({_id:1, productName:"Striped Tie", price:65.99, description:"black and blue silk tie"});'

- sleep 15
- cd tests
- npm install mocha
- npm install chai
- npm install chai-http
- npm install superagent

services:
- mongodb
